### PR TITLE
Update to Ignition Edifice

### LINKED ISSUE #7: Ignition Edifice migration
### Description

RMF so far has been built and used with Ignition Dome, now that [Ignition Edifice has been released](https://discourse.ros.org/t/ignition-edifice-release-get-a-t-shirt/19726) we should start migrating to it so we can try to experiment with some of the newest features (i.e. lightmaps, sky textures, the new GUI plugins or even Collada exporters).

### Implementation considerations

There _should_ be no major behavior change and it should be as simple as changing the semver library version in the CMakeLists / package.xml as well as updating the documentation, but testing to make sure no regressions are introduced is required.

### PR DESCRIPTION
**Pull request by luca-della-vedova**
### Implemented feature

Update dependencies to Ignition Edifice. Requires [rmf_demos #22](https://github.com/open-rmf/rmf_demos/pull/22) and [rmf_traffic_editor #330](https://github.com/open-rmf/rmf_traffic_editor/pull/330). Fixes #7 . Will also require updating the docs under `rmf_demos` once they are merged

### Implementation description

Version bump of all the libraries that have been updated in Ignition Edifice.
Sdformat is now a lot less tolerant on deviations from the specification (hence the required PRs). Did some quick testing on scenarios with various features (robots, doors, delivery requests, crowdsim) and there seem to be no regressions.
To test install Ignition Edifice
`sudo apt install ignition-edifice`
and do a clean build of the workspace.

### CODE REVIEW

**Comment by tanyouliang95** [comment]
I briefly tested this change with the different demo worlds. Looks fine to me. :+1: 

One concern might be regarding the `rosdep` installation for `ignition-edifice`. Will need to test the full [installation](https://github.com/open-rmf/rmf/blob/main/rmf.repos) pipeline in a clean workspace and env, to make sure all relevant ign dependencies are installed. Also, as stated, will need to update the CI in `rmf_demos`.

**Comment by luca-della-vedova** [comment]
> I briefly tested this change with the different demo worlds. Looks fine to me. +1
> 
> One concern might be regarding the `rosdep` installation for `ignition-edifice`. Will need to test the full [installation](https://github.com/open-rmf/rmf/blob/main/rmf.repos) pipeline in a clean workspace and env, to make sure all relevant ign dependencies are installed. Also, as stated, will need to update the CI in `rmf_demos`.

Yea sadly ignition-edifice is not in `rosdep` (same as ignition-dome) so it has to be installed manually. This will probably be fixed in Galactic / Fortress but it's still at least a few months away and will have to be installed manually for the time being.

**Comment by tanyouliang95** [comment]
Yikes, In this case we will need indicate `sudo apt install `ignition-edifice` in CI and installation.

**Comment by luca-della-vedova** [comment]
> Yikes, In this case we will need indicate `sudo apt install `ignition-edifice` in CI and installation.

Yea I was waiting for the docs PR to be merged, we will have to update dome to edifice in both CI and docs under `rmf_demos`.
I expect the rmf_demos [PR](https://github.com/open-rmf/rmf_demos/pull/24) to break CI and become green once this is merged

**Review by tanyouliang95 — APPROVED** [review]
LGTM

**Pull request merged**
