### PR TITLE
Upgrade to Ignition Fortress

### LINKED ISSUE #69: Upgrade to Ignition Fortress
### Description

Ignition plugins are currently targeting Ignition Edifice and ROS2 Galactic. We should migrate to Fortress for ROS2 Jammy to have them run on LTS platforms.

### Implementation considerations

Work started in the `feature/ignition_fortress` branch but was stalled because binaries of ros_ign were missing. Since they will be released together with Humble we should probably migrate our plugins by Humble release time

### PR DESCRIPTION
**Pull request by luca-della-vedova**
### Implemented feature

Closes #69, migrating to Ignition Fortress.

### Implementation description

Together with bumping dependencies on `CMakeLists` and `package.xml`, we can use a new utility function to enable components which allows us to remove a lot of boilerplate component creation code resulting in a hundred or so lines of code being removed.
Note that this PR will make the binary `ros_ign` available in Galactic incompatible with rmf_simulation since the `ros_ign` package in galactic supports Edifice while the `ros_ign` in Rolling (and future Humble) will support Fortress.
Hence users who wish to use Ignition Fortress with Galactic should switch to build `ros_ign` from source

### CODE REVIEW

**Review by aaronchongth — CHANGES_REQUESTED** [review]
Thanks for handling the migration! I've been running some tests and have been unable to get loop requests to run for more than 1 loop. I tried using both the RMF panel and dashboard to issue the request, Could you help take a look into that, just in case it is happening only on my end?

Could you perhaps start a PR to add `ros_ign` to `rmf/rmf.repos` as well? Might be a good idea to have that merged in first before this migration.

**Comment by luca-della-vedova** [comment]
> Thanks for handling the migration! I've been running some tests and have been unable to get loop requests to run for more than 1 loop. I tried using both the RMF panel and dashboard to issue the request, Could you help take a look into that, just in case it is happening only on my end?
> 

I can reproduce the issue with loop requests with more than one loop not happening, it seems once the first loop is finished the robot doesn't receive a new path request so my guess is that the robot's state estimation by the fleet adapter puts it in some state where it doesn't detect the robot's first loop as completed, hence doesn't issue the followup loop request.
It's tricky since really 90% of the logic between Gazebo and Ignition happens in a common source so there should really not be such an issue.
I see this behavior in `main` also so I guess it's not necessarily related to this PR? But I agree it's quite a deal breaker, will look into it.

> Could you perhaps start a PR to add `ros_ign` to `rmf/rmf.repos` as well? Might be a good idea to have that merged in first before this migration.

Done https://github.com/open-rmf/rmf/pull/144

**Comment by aaronchongth** [comment]
> I see this behavior in main also so I guess it's not necessarily related to this PR? But I agree it's quite a deal breaker, will look into it.
Yup, as long as we know that it is not related to this PR we can just start an issue. I can spend a little bit more time to diagnose it.

Per DM, after the lift plugin segfault is fixed, this should be good to merge.

**Comment by luca-della-vedova** [comment]
> Per DM, after the lift plugin segfault is fixed, this should be good to merge.

Should be good now https://github.com/open-rmf/rmf_simulation/pull/70/commits/254d720375f175b5debf3cda4a2bfc389c7893bb

**Pull request merged**
