### PR TITLE
Add support for gz harmonic.

### PR DESCRIPTION
**Pull request by arjo129**
Opening for visibility. This branch adds support for gz harmonic.

### CODE REVIEW

**Comment by Yadunund** [comment]
Any downside to merging this into `main` since `harmonic` is LTS? We won't backport to older distros.

**Comment by arjo129** [comment]
I don't think gazebo harmonic can live next to gazebo classic so it has big implications.

**Comment by Yadunund** [comment]
But I don't think gazebo classic will be supported on 24.04/Jazzy so we have to get rid of it from `main` before Rolling switches to 24.04  (around April 2024). Maybe we can combine the removal into this PR but save it for merge until Rolling migrates to the new OS on the buildfarm.

**Comment by luca-della-vedova** [comment]
> But I don't think gazebo classic will be supported on 24.04/Jazzy so we have to get rid of it from `main` before Rolling switches to 24.04 (around April 2024). Maybe we can combine the removal into this PR but save it for merge until Rolling migrates to the new OS on the buildfarm.

Sounds good, I would also suggest removing the split into `gz` and `common` since the `common` package was only meant to allow shared logic between classic and gz, which won't really be necessary anymore.
I'll work on the refactor and push it here. I believe that by moving away from the `common` approach we could do a more ECS based simulation where there is (for example) only one ROS 2 node for all the doors, rather than one per door. I started some work on this [here](https://github.com/open-rmf/rmf_simulation/tree/luca/ecs_plugins_sandbox) but will resurrect it

**Comment by arjo129** [comment]
Merged into #114

**Pull request closed without merging**
